---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
  - datadisk-n01611109
  - profile-n01611109
  - user-n01611109
  - webserver-n01611109

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"